# Generated by Django 4.1.5 on 2023-02-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nginx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=15)),
                ('enable', models.BooleanField(default=False)),
                ('extra_config', models.CharField(default='\n        ssl_prefer_server_ciphers on;\n        ssl_ciphers EECDH+AESGCM:EDH+AESGCM;\n        ssl_ecdh_curve secp384r1;\n        ssl_session_cache shared:SSL:10m;\n    ', max_length=500)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nginx', to='xview.certificate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
